language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: m0sVL2dvgvV8OiJXLbwejFT04ODhZYecu34mNmSO6QbFHmY8nmaotJneTI6CP1nHnifLISH7NhNIvCk5vMd7Op894F6Ju4F3HviE/1796wbb2chWP04FtGKxmkAe9CgqP0LteoRaUZHgpDDEfC/5wQg7umWZQBCLvmP2o3fpgSd9vuhDOamk6BXWqn9Kz7ommFL2cYHR3AwyJSaHn7Irq6abNiFPRDPefD10K73KpCtd/a6s/U/I3ZG2o4P6HZKf/X0lktu5qrM9Gm+0E2qqBBO8gbcOHuHMmuCoqQMhvj3XtqhPvnu0Wmji7DdutfOQ6lcrR33xu98Y7OM9nsJZfHchhEUKPfBuSHV5WeVVxprOfBxkUNeE6AJrNEchkvTMJIHD/a/LjwL7ZGh4wPJ1nD94fxn68iRNNVEUa+AtQUyeYJsARXHNiX6fBjJzXhR70FqorueAp5oFVM3ZRCEqz/YkEcNhOl17tk4Cs4uTzMbm9l5wWrXurWmBsJcNiiOY9YWH/qnpW3EW7cXadEW5umf8OOF2T57ezrBV69MP64lqRhB//otS60lii9Uxlkg+uDmc+5opjKzxn29DOgs7R0Sc2nDfcFKDom4l+OQQEr1aFb5rdvWdQWXMLYb7pG3prohOW0W1fQ/YRxKesKUfKwV/8QidCCMpAfPWPcEMuSM=
